# Site Settings
baseurl: 		""
title: 			Willsie

name: 			Willsie
description: 	A beautifully contemporary and elegant Jekyll theme
url: 			"http://localhost:4000"


paginate: 		3
paginate_path: 	"blog/page:num"

twitter: 		indiqo
email: 			hello@indiqo.eu

disqus: 		your_disqus_shortname
analytics: 		UA-XXXXXXX-Y

copyright: 		Copyright 2022 Willsie.	

# Build Settings
permalinks: 	pretty

plugins: [jekyll-paginate]